import { ProjectCard, ShowcaseLink } from './types';

export const SEED_PROJECTS: ProjectCard[] = [
  {
    "id": "1",
    "slug": "samawah-contracts",
    "title_ar": "عقود سماوة",
    "subtitle_ar": "منصة ذكية لإنشاء ومراجعة العقود",
    "short_description_ar": "حوّل صياغة العقود إلى تجربة منظمة وسريعة.",
    "project_url": "https://samawah-docs-web.vercel.app/",
    "cover_image_url": "/projects/contracts.png",
    "category": "Legal Tech",
    "tags": ["AI", "Contracts", "Automation"],
    "accent_color": "#2563eb",
    "is_visible": true,
    "is_featured": true,
    "sort_order": 1,
    "status": "published",
    "created_at": new Date().toISOString(),
    "updated_at": new Date().toISOString()
  },
  {
    "id": "2",
    "slug": "samawah-team",
    "title_ar": "فريق سماوة",
    "subtitle_ar": "لوحة داخلية لإدارة المشاريع والمهام",
    "short_description_ar": "نظّم المشاريع والمهام في مساحة تشغيل واحدة.",
    "project_url": "https://samawah-team-app-sepia.vercel.app/dashboard",
    "cover_image_url": "/projects/team-manage.png",
    "category": "Internal Tool",
    "tags": ["Dashboard", "Tasks", "Team"],
    "accent_color": "#10b981",
    "is_visible": true,
    "is_featured": false,
    "sort_order": 2,
    "status": "published",
    "created_at": new Date().toISOString(),
    "updated_at": new Date().toISOString()
  },
  {
    "id": "3",
    "slug": "samawah-store",
    "title_ar": "متجر سماوة",
    "subtitle_ar": "واجهة للمنتجات والإصدارات الثقافية",
    "short_description_ar": "متجر رقمي أنيق لعرض وبيع منتجات سماوة.",
    "project_url": "https://samawah-store.vercel.app/",
    "cover_image_url": "/projects/store.png",
    "category": "E-commerce",
    "tags": ["Store", "Culture", "Products"],
    "accent_color": "#f43f5e",
    "is_visible": true,
    "is_featured": false,
    "sort_order": 3,
    "status": "published",
    "created_at": new Date().toISOString(),
    "updated_at": new Date().toISOString()
  },
  {
    "id": "4",
    "slug": "sadeed",
    "title_ar": "سديد",
    "subtitle_ar": "تجربة ذكاء اصطناعي بطابع سعودي",
    "short_description_ar": "منصة ذكية تحتاج توصيفاً نهائياً بعد فحص الواجهة.",
    "project_url": "https://sadeed-sa.netlify.app/",
    "cover_image_url": "/projects/nazl.png",
    "category": "AI",
    "tags": ["AI", "Saudi", "Assistant"],
    "accent_color": "#059669",
    "is_visible": true,
    "is_featured": false,
    "sort_order": 4,
    "status": "published",
    "created_at": new Date().toISOString(),
    "updated_at": new Date().toISOString()
  },
  {
    "id": "5",
    "slug": "inviteauto",
    "title_ar": "عزّام",
    "subtitle_ar": "أتمتة الدعوات والرسائل الذكية",
    "short_description_ar": "أرسل دعوات مخصصة بكفاءة وراقب النتائج.",
    "project_url": "https://www.inviteauto.com/",
    "cover_image_url": "/projects/reports.png",
    "category": "Automation",
    "tags": ["Invites", "Automation", "Campaigns"],
    "accent_color": "#2563eb",
    "is_visible": true,
    "is_featured": false,
    "sort_order": 5,
    "status": "published",
    "created_at": new Date().toISOString(),
    "updated_at": new Date().toISOString()
  },
  {
    "id": "6",
    "slug": "ratbha-ai",
    "title_ar": "رتّبها AI",
    "subtitle_ar": "مخطط يومي ذكي للمهام والتقويم",
    "short_description_ar": "رتّب يومك بالصوت والشات والتقويم الذكي.",
    "project_url": "https://ratbha-ai.vercel.app/",
    "cover_image_url": "/projects/kharbasha.png",
    "category": "Productivity",
    "tags": ["AI", "Planner", "Calendar"],
    "accent_color": "#f59e0b",
    "is_visible": true,
    "is_featured": false,
    "sort_order": 6,
    "status": "published",
    "created_at": new Date().toISOString(),
    "updated_at": new Date().toISOString()
  },
  {
    "id": "7",
    "slug": "nazl",
    "title_ar": "نزل",
    "subtitle_ar": "منصة رقمية لخدمات السكن والضيافة",
    "short_description_ar": "منصة عقارية وسكنية متكاملة.",
    "project_url": "https://nazl.vercel.app/",
    "cover_image_url": "/projects/nazl.png",
    "category": "Platform",
    "tags": ["Platform", "Web App"],
    "accent_color": "#0ea5e9",
    "is_visible": true,
    "is_featured": false,
    "sort_order": 7,
    "status": "published",
    "created_at": new Date().toISOString(),
    "updated_at": new Date().toISOString()
  },
  {
    "id": "8",
    "slug": "kharbasha",
    "title_ar": "خربشة",
    "subtitle_ar": "أداة ذكية لاستخراج وتنظيم البيانات",
    "short_description_ar": "حوّل صفحات الويب إلى بيانات منظمة قابلة للاستخدام.",
    "project_url": "https://kharbasha-platform.vercel.app/",
    "cover_image_url": "/projects/kharbasha.png",
    "category": "Data AI",
    "tags": ["AI", "Data", "Scraping"],
    "accent_color": "#ec4899",
    "is_visible": true,
    "is_featured": false,
    "sort_order": 8,
    "status": "published",
    "created_at": new Date().toISOString(),
    "updated_at": new Date().toISOString()
  }
];

export const FALLBACK_LINKS: ShowcaseLink[] = [
  {
    id: 'link-home-default',
    slug: 'default',
    title_ar: 'كل المشاريع المميزة',
    description_ar: 'مجموعة المشاريع المفضلة كمشهد عام',
    project_ids: ['1', '2', '3', '4'],
    sort_order: 1,
    is_active: true,
    starts_at: null,
    ends_at: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'link-investors',
    slug: 'investors',
    title_ar: 'روابط عرض المستثمرين',
    description_ar: 'مشاريع مختارة بعناية للمستثمرين',
    project_ids: ['1', '4', '6'],
    sort_order: 2,
    is_active: true,
    starts_at: null,
    ends_at: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
